smarthome/portal/urls.py
from django.urls import path

from . import views

app_name = 'portal'
urlpatterns = [
    path('', views.home, name='home'),
    path('selector', views.selector, name='selector'),
    path('smarthome/<str:pk>', views.viewSmarthome, name='viewSmarthome'),
    path('getStatesDevice', views.getStatesDevice, name='getStatesDevice'),
    path('editNameDevice', views.editNameDevice, name='editNameDevice')
]

smarthome/smarthome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from authentication.forms import LoginForm, MyPasswordResetForm, MyPasswordChangeForm, MySetPasswordForm

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('portal.urls')),
    path('settings/', include('settings.urls')),
    path('', include('authentication.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login.html',
                                                         authentication_form=LoginForm,
                                                         redirect_authenticated_user='/')),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(
        form_class=MyPasswordResetForm, html_email_template_name='registration/password_reset_email.html')),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(form_class=MySetPasswordForm)),
    path('accounts/password_change/',
         auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html',
                                               form_class=MyPasswordChangeForm)),
    path('accounts/', include('django.contrib.auth.urls')),
]

handler404 = 'portal.views.error_404'

smarthome/portal/models.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models


class Smarthome(models.Model):
    unique_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    url = models.CharField('URL', max_length=255, unique=True)
    token = models.CharField('Token умного дома', max_length=255)
    description = models.CharField('Описание умного дома', max_length=255, blank=True, default='')
    isActive = models.BooleanField('Доступность умного дома (нужно для мониторинга)', default=True)

    def __str__(self):
        return self.url

    class Meta:
        ordering = ['url']
        verbose_name = 'Умный дом'
        verbose_name_plural = 'умные дома'


class AccessSmarthome(models.Model):
    ACCESS = (('guest', 'Гость'),
              ('owner', 'Владелец'))
    unique_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    smarthome = models.ForeignKey(Smarthome, on_delete=models.CASCADE, verbose_name='ID умного дома')
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, verbose_name='Пользователь')
    access = models.CharField('', max_length=5, choices=ACCESS, null=True)
    isConfirmed = models.BooleanField('Пользователь подтвердил запрос', default=False)

    def __str__(self):
        return self.smarthome.url + ' - ' + self.user.username

    class Meta:
        ordering = ['user']
        verbose_name = 'уровень доступа к умному дому'
        verbose_name_plural = 'Уровень доступа к умному дому'
        unique_together = [['smarthome', 'user']]


class Device(models.Model):
    unique_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    smarthome = models.ForeignKey(Smarthome, on_delete=models.CASCADE, verbose_name='ID умного дома')
    codeDevice = models.CharField('2 часть entity_id', max_length=255)
    domain = models.CharField('Domain (1 часть entity_id)', max_length=255)
    device_class = models.CharField('Класс устройства', max_length=255, blank=False, null=True)
    friendly_name = models.CharField('Название из HomeAssistant', max_length=255)
    name = models.CharField('Введённоё название устройства', max_length=255)
    icon = models.CharField('Иконка для сенсоров', max_length=255, blank=True, null=True)
    unit_of_measurement = models.CharField('Единица измерения', max_length=255, blank=True, null=True)

    def __str__(self):
        return self.smarthome.url + ' - ' + self.codeDevice

    def getEntityId(self):
        return self.domain + '.' + self.codeDevice

    class Meta:
        verbose_name = 'устройство'
        verbose_name_plural = 'Устройства'
        unique_together = [['domain', 'codeDevice']]


class DeviceStates(models.Model):
    unique_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    device = models.ForeignKey(Device, on_delete=models.CASCADE, verbose_name='Устройство')
    state = models.CharField('Состояние устройства', max_length=255, blank=True)
    last_changed = models.DateTimeField('Последнее изменение состояния')
    last_updated = models.DateTimeField('Последнее обновление')

    def __str__(self):
        return self.device.friendly_name + ' - ' + self.state

    class Meta:
        ordering = ['-last_updated']
        verbose_name = 'состояние устройства'
        verbose_name_plural = 'Состояния устройств'
        unique_together = [['device', 'state', 'last_changed', 'last_updated']]

smarthome/portal/forms.py
from django import forms

from portal.models import Smarthome


class SmarthomeForm(forms.ModelForm):
    # url = forms.CharField(label='Введите URL', widget=forms.TextInput(attrs={'class': 'form-control'}))
    # token = forms.CharField(label='Введите токен', widget=forms.TextInput(attrs={'class': 'form-control'}))
    # description = forms.CharField(label='Введите описание', widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Smarthome
        fields = ('url', 'token', 'description',)
        widgets = {'url': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'https://domain'}),
                   'token': forms.TextInput(attrs={'class': 'form-control'}),
                   'description': forms.TextInput(attrs={'class': 'form-control'})}

smarthome/portal/views.py
import json
import requests
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from pytz import timezone

from portal.models import AccessSmarthome, Device, DeviceStates, Smarthome


def home(request):
    """
    :param request:
    :return:

    Главная страница портала. Показывается только неавторизованным пользователям. Если пользователь имеет доступ только
    к одному умному дому, то открывается страница :view:`portal.views.viewSmarthome`. Если у пользователя нет доступа ни к
    одному умному дому или есть доступ к нескольким, то открывается страница "Настройки" :view:`settings.views.settings`.

    **Context**

    ``countSmarthome`` Количество умных домов, доступных текущему пользователю.

    **Template**

    :template:`portal/home.html`
    """
    if request.user.is_authenticated:
        countSmarthome = len(AccessSmarthome.objects.filter(user=request.user, isConfirmed=True))
        if countSmarthome == 0 or countSmarthome > 1:
            return redirect('settings:settings')
        elif countSmarthome == 1:
            return redirect('portal:viewSmarthome', AccessSmarthome.objects.get(user=request.user, isConfirmed=True).pk)
    return render(request, 'home.html')


def getListId(x):
    try:
        device_class = x['attributes']['device_class']
    except:
        device_class = None
    try:
        icon = x['attributes']['icon']
    except:
        icon = None
    try:
        unit_of_measurement = x['attributes']['unit_of_measurement']
    except:
        unit_of_measurement = None

    return {'domain': x['entity_id'].split('.')[0], 'codeDevice': x['entity_id'].split('.')[1],
            'device_class': device_class, 'icon': icon, 'friendly_name': x['attributes']['friendly_name'],
            'unit_of_measurement': unit_of_measurement, 'state': {
            'state': x['state'], 'last_changed': x['last_changed'],
            'last_updated': x['last_updated']}}


def addState(x):
    x.state = DeviceStates.objects.filter(device_id=x.pk)[0]


@login_required
def viewSmarthome(request, pk):
    """
    :param request: Запрос от пользователя
    :param pk: Идентификатор записи из таблицы :model"`settings.AccessSmarthome`
    :return:

    Отображение данных умного дома на текущий момент. Если pk не найдено, то возвращается 404 ошибка.
    Если запись найдена, но принадлежит другому пользователю, то возвращается 403 ошибка.
    Если всё нормально, то возвращается страница с состоянием умного дома на данный момент.

    **Models**

    :model:`settings.AccessSmarthome`

    **Template**

    :template:`viewSmarthome.html`
    """
    access = AccessSmarthome.objects.filter(pk=pk, isConfirmed=True)
    if access.exists():
        if access[0].user == request.user:
            headers = {'Authorization': "Bearer %s" % access[0].smarthome.token}
            sensors = []
            lights = []
            switches = []
            groups = {'switch': 0, 'light': 0}
            state = {'off': 0, 'on': 1}
            try:
                responseDevice = requests.get(access[0].smarthome.url + '/api/states', headers=headers, timeout=10).json()
                devices = list(map(getListId, filter(lambda x: 'friendly_name' in list(x['attributes'].keys()),
                                                     responseDevice)))
                for device in devices:
                    pkDevice = ''
                    if Device.objects.filter(domain=device['domain'], codeDevice=device['codeDevice']).exists():
                        oldDevice = Device.objects.get(domain=device['domain'], codeDevice=device['codeDevice'])
                        oldDevice.friendly_name = device['friendly_name']
                        oldDevice.save()
                        pkDevice = oldDevice.pk
                    else:
                        newDevice = Device(smarthome=access[0].smarthome, domain=device['domain'].split('.')[0],
                                           codeDevice=device['codeDevice'], device_class=device['device_class'],
                                           friendly_name=device['friendly_name'], name=device['friendly_name'],
                                           icon=device['icon'], unit_of_measurement=device['unit_of_measurement'])
                        newDevice.save()
                        pkDevice = newDevice.pk
                    newDeviceStates = DeviceStates(device_id=pkDevice, state=device['state']['state'],
                                                   last_changed=device['state']['last_changed'],
                                                   last_updated=device['state']['last_updated'])
                    try:
                        newDeviceStates.full_clean()
                        newDeviceStates.save()
                    except ValidationError:
                        pass
            except:
                pass

            devices = Device.objects.filter(smarthome=access[0].smarthome).order_by('friendly_name')
            for device in devices:
                try:
                    stateRecord = DeviceStates.objects.filter(device=device)[0]
                    device.state = stateRecord.state
                    if device.domain in ['sensor', 'binary_sensor']:
                        sensors.append(device)
                    if device.domain == 'light':
                        lights.append(device)
                        groups[device.domain] += state[device.state]
                    if device.domain == 'switch':
                        switches.append(device)
                        groups[device.domain] += state[device.state]
                except IndexError:
                    pass

            if groups['switch'] != len(switches):
                groups['switch_state'] = 'toggle_off'
            else:
                groups['switch_state'] = 'toggle_on'

            if groups['light'] != len(lights):
                groups['light_state'] = 'toggle_off'
            else:
                groups['light_state'] = 'toggle_on'

            groups['light_len'] = len(lights)
            groups['switch_len'] = len(switches)
            return render(request, 'viewSmarthome.html', {'sensors': sensors, 'lights': lights, 'switches': switches,
                                                          'groups': groups, 'pk': access[0].pk})
        return HttpResponse(status=403)
    return HttpResponse(status=404)


@login_required
@csrf_exempt
def selector(request):
    access = AccessSmarthome.objects.filter(pk=request.POST['pk'], isConfirmed=True)
    if access.exists():
        if access[0].user == request.user and access[0].access != 'guest':
            url = "%s/api/services/%s/%s" % (access[0].smarthome.url, request.POST['domain'], request.POST['service'])
            headers = {'Authorization': "Bearer %s" % access[0].smarthome.token}
            data = json.dumps({"entity_id": request.POST['entity_id']})
            try:
                response = requests.post(url, headers=headers, data=data)
            except:
                return HttpResponse(status=503)
            return HttpResponse(response.status_code)
        return HttpResponse(status=403)
    return HttpResponse(status=404)


@login_required
def getStatesDevice(request):
    moscowTimezone = timezone('Europe/Moscow')

    def transformState(x):
        if x.device.unit_of_measurement is not None:
            return x.state
        else:
            if x.state == 'off':
                return 0
            else:
                return 1

    access = AccessSmarthome.objects.filter(pk=request.GET['pk'], isConfirmed=True)
    if access.exists():
        if access[0].user == request.user and access[0].access != 'guest':
            devices = Device.objects.filter(domain=request.GET['entity_id'].split('.')[0],
                                            smarthome=access[0].smarthome,
                                            codeDevice=request.GET['entity_id'].split('.')[1])
            if devices.exists():
                states = DeviceStates.objects.filter(device=devices[0])
                if states.exists():
                    label = devices[0].unit_of_measurement
                    response = {'type': 'line', 'data': {
                        'labels': list(
                            map(lambda x: x.last_changed.astimezone(moscowTimezone).strftime('%d.%m %H:%M:%S'),
                                states.order_by('last_changed'))),
                        'datasets': [{
                            # 'backgroundColor': 'rgba(0, 0, 204, 0.9)',
                            'borderColor': 'rgba(0, 0, 204, 0.6)',
                            'label': label if label is not None else '0 - выключено, 1 - включено',
                            'data': list(map(transformState, states.order_by('last_changed'))),
                            'borderWidth': 1,
                            'steppedLine': True,
                            'fill': False
                        }]}, 'options': {'scales': {'yAxes': [{'ticks': {'beginAtZero': False}}]}}}
                    return JsonResponse(response, safe=False)
                return HttpResponse(status=204)
            return HttpResponse(status=400)
        return HttpResponse(status=403)
    return HttpResponse(status=404)


def editNameDevice(request):
    access = AccessSmarthome.objects.filter(pk=request.GET['pk'], isConfirmed=True)
    if access.exists():
        if access[0].user == request.user and access[0].access != 'guest':
            print(access[0].smarthome.pk)
            devices = Device.objects.filter(domain=request.GET['entity_id'].split('.')[0],
                                            smarthome=access[0].smarthome,
                                            codeDevice=request.GET['entity_id'].split('.')[1])

smarthome/portal/templates/block.html
<div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6" style="cursor: default">
    <ul class="list-group mb-4">
        <li class="list-group-item active d-flex justify-content-between align-items-center"
            entity_id="{{ domain }}.all" count_all="{{ count_all }}">
            {{ name }}
            <span class="badge badge-pill">
                <i class="material-icons toggle" style="cursor: pointer"
                   onclick="selector('{{ domain }}.all', '{{ pk }}')">
                    {{ toogle_block }}
                </i>
            </span>
        </li>
        {% for device in devices %}
            <li class="list-group-item d-flex justify-content-between align-items-center block {{ domain }}"
                pk="{{ pk }}" entity_id="{{ device.getEntityId }}" data-toggle="modal" data-target="#infoDeviceModal">
                <span class="badge badge-pill">
                    {% if device.state == 'on' %}
                        <i class="material-icons flash" style="color: rgb(253, 216, 53);"> {{ flash }} </i>
                    {% else %}
                        <i class="material-icons flash"> {{ flash }} </i>
                    {% endif %}
                </span>
                <span class="nameDevice" style="font-size: 22px; cursor: pointer">
                    {{ device.name }}
                </span>
                <span class="badge badge-pill">
                    <i class="material-icons toggle" style="cursor: pointer"
                       onclick="selector('{{ device.getEntityId }}', '{{ pk }}')">
                        {% if device.state == 'on' %}
                            toggle_on
                        {% else %}
                            toggle_off
                        {% endif %}
                    </i>
                </span>
            </li>
        {% endfor %}
    </ul>
</div>

smarthome/portal/templates/home.html
{% extends 'application.html' %}
{% block title %}Главная страница{% endblock %}
{% block content %}
    {% if not user.is_authenticated %}
        <div class="fullscreen__container" style="flex: 1; display: flex; justify-content: center; align-items: center">
            <div class="container">
                <div class="jumbotron">
                    <div class="jumbotron">
                        <h1 class="display-4">Система управления умным домом</h1>
                        <p class="lead">С помощью данного портала можно управлять умным домом, построенном на
                            инфраструктуре Home Assistant.</p>
                        <hr class="my-4">
                        <p>Для использования портала надо пройти регистрацию и ввести URL и token вашей системы.</p>
                        <a class="btn btn-primary btn-lg" href="https://www.home-assistant.io/" role="button">
                            Узнать больше о Home Assistant
                        </a>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
    {% endif %}
{% endblock %}

smarthome/portal/templates/viewSmarthome.html
{% extends 'application.html' %}
{% block title %}Умный дом{% endblock %}
{% block content %}
    <script>
        $(document).ready(function () {
            $('#infoDeviceModal').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget) // Button that triggered the modal
                var nameDevice = button.find('.nameDevice') // Extract info from data-* attributes
                // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
                // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
                var modal = $(this)
                var infoDeviceModalTitle = modal.find('#infoDeviceModalTitle')
                infoDeviceModalTitle.text(nameDevice.text())

                var editButton = $('<small>', {
                    'class': 'text-muted', 'text': 'Изменить', 'style': 'cursor: pointer',
                })
                editButton.on('click', function () {
                    var lastText = $('#infoDeviceModalTitle').text().trim().replace('Изменить', '')
                    $('#infoDeviceModalTitle').html('<div class="input-group">' +
                        '<input type="text" class="form-control" placeholder="' + lastText + '" ' +
                        'onkeypress="saveNameDevice(this)"></div>')
                })
                $(infoDeviceModalTitle).append(editButton)

                var edit = $('span', {'class': 'material-icons', 'text': 'edit'})

                var ctx = document.getElementById('graphStates');
                var pk = $(button).attr('pk')
                var entity_id = $(button).attr('entity_id')
                infoDeviceModalTitle.attr('pk', pk)
                infoDeviceModalTitle.attr('entity_id', entity_id)
                $.ajax("{% url 'portal:getStatesDevice' %}", {
                    data: {'pk': pk, 'entity_id': entity_id},
                    statusCode: {
                        200: function (data) {
                            graphStates = new Chart(ctx, data);
                        },
                        204: function () {
                            alert('Нет данных об устройстве')
                        },
                        400: function () {
                            alert('Устройство не найдено')
                        },
                        403: function () {
                            alert('Нет доступа к информации об устройстве')
                        },
                        404: function () {
                            alert('Устройство не найдено')
                        },
                        503: function () {
                            alert('Умный дом недоступен. Попробуйте ещё раз')
                        }
                    }
                })
            })
            $('#infoDeviceModal').on('hide.bs.modal', function (event) {
                try {
                    graphStates.destroy()
                } catch (e) {

                }
            })
        })

        function saveNameDevice(el) {
            if (event.which === 13) {
                $.ajax("{% url 'portal:editNameDevice' %}", {
                    data: {
                        'pk': $(el).parent().parent().attr('pk'),
                        'entity_id': $(el).parent().parent().attr('entity_id'), 'name': $(el).val()
                    },
                    statusCode: {
                        200: function () {
                            location.reload()
                        },
                        400: function () {
                            alert('Устройство не найдено')
                            location.reload()
                        },
                        403: function () {
                            alert('Нет доступа к изменению названий устройства')
                            location.reload()
                        },
                        404: function () {
                            alert('Не найден доступ к умному дому')
                            location.reload()
                        }
                    }
                })
            }
        }

        function cancelEditNameDevice(lastName) {
            $('#infoDeviceModalTitle').text()
        }


        var table = {
            "toggle_on": ["toggle_off", "turn_off", "black"],
            "toggle_off": ["toggle_on", "turn_on", "rgb(253, 216, 53)"]
        };

        function all_toggles(domain) {
            var count_all = Number($('li[entity_id="' + domain + '.all"]').attr('count_all'));
            var count = $('.' + domain + ':contains("toggle_on")').length;
            if (count === count_all)
                $('li[entity_id="' + domain + '.all"] .toggle').text('toggle_on');
            else
                $('li[entity_id="' + domain + '.all"] .toggle').text('toggle_off');
        }

        function selector(entity_id, pk) {
            var toggle = $('li[entity_id="' + entity_id + '"] .toggle');
            var state = toggle.text().trim();

            if (entity_id.split('.')[1] !== 'all') {
                setToggle(entity_id, state, pk);
            } else {
                list = $('.' + entity_id.split('.')[0]);
                $.each(list, function (item, value) {
                    setToggle($(value).attr('entity_id'), state, pk)
                });
                toggle.text(table[state][0]);
            }
        }

        function setToggle(entity_id, state, pk) {
            var toggle = $('li[entity_id="' + entity_id + '"] .toggle');
            if (entity_id.split('.')[0] !== 'all') {
                var flash = $('li[entity_id="' + entity_id + '"] .flash');
                $.ajax("{% url 'portal:selector' %}", {
                    type: 'POST',
                    data: {
                        'domain': entity_id.split('.')[0],
                        'entity_id': entity_id,
                        'service': table[state][1],
                        'pk': pk
                    },
                    statusCode: {
                        200: function () {
                            toggle.text(table[state][0]);
                            flash.css('color', table[state][2]);
                            all_toggles(entity_id.split('.')[0])
                        },
                        403: function () {
                            alert('Нет доступа к изменению состояний устройства')
                        },
                        404: function () {
                            alert('Устройство не найдено')
                        },
                        503: function () {
                            alert('Умный дом недоступен. Попробуйте ещё раз')
                        }
                    }
                })
            }
        }
    </script>
    <div class="container mt-4">
        <div class="row">
            <div class="col-12">
                <div class="card mb-4">
                    <div class="card-header" style="background-color: #007bff; color: white">Сенсоры</div>
                    <div class="card-body">
                        <div class="row row-cols-2 row-cols-sm-2 row-cols-md-3 row-cols-lg-5">
                            {% for sensor in sensors %}
                                <div class="col mb-4">
                                    <div class="card block" data-toggle="modal" data-target="#infoDeviceModal"
                                         pk="{{ pk }}" entity_id="{{ sensor.getEntityId }}">
                                        <div class="card-body text-center" style="cursor: pointer">
                                            <p class="card-text" style="font-size: 20px;">
                                                {% if sensor.device_class == 'door' %}
                                                    <i class="material-icons">
                                                        {% if sensor.state == 'off' %}
                                                            no_meeting_room
                                                        {% else %}
                                                            meeting_room
                                                        {% endif %}
                                                    </i>
                                                {% elif sensor.device_class == 'motion' %}
                                                    <i class="material-icons"> directions_walk </i>
                                                {% elif sensor.domain == 'binary_sensor' %}
                                                    <i class="material-icons">
                                                        {% if sensor.state == 'on' %}
                                                            check_circle
                                                        {% else %}
                                                            panorama_fish_eye
                                                        {% endif %}
                                                    </i>
                                                {% else %}
                                                    {{ sensor.state|default:'&nbsp' }}
                                                    {{ sensor.unit_of_measurement|default:'&nbsp' }}
                                                {% endif %}
                                            </p>
                                            <p class="card-text"><small class="text-muted nameDevice">
                                                {{ sensor.name }}
                                            </small>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            {% include "block.html" with domain='light' name='Освещение' devices=lights flash='wb_incandescent' toogle_block=groups.light_state count_all=groups.light_len %}
            {% include "block.html" with domain='switch' name='Выключатели' devices=switches flash='flash_on' toogle_block=groups.switch_state count_all=groups.switch_len %}
        </div>
    </div>

    <div class="modal fade" id="infoDeviceModal" data-backdrop="static" data-keyboard="false" tabindex="-1"
         aria-labelledby="infoDeviceModalTitle" style="display: none;" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="infoDeviceModalTitle">

                    </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <canvas id="graphStates"></canvas>
                </div>
            </div>
        </div>
    </div>
{% endblock %}